# Generated by Django 5.2.8 on 2026-01-26 04:04

from django.db import migrations


def create_membership_statuses(apps, schema_editor):
    MembershipStatus = apps.get_model('members_amor108', 'MembershipStatus')
    if not MembershipStatus.objects.filter(name='Approved').exists():
        MembershipStatus.objects.create(name='Approved', description='Member application has been approved.')
    if not MembershipStatus.objects.filter(name='Rejected').exists():
        MembershipStatus.objects.create(name='Rejected', description='Member application has been rejected.')
    if not MembershipStatus.objects.filter(name='Pending Approval').exists():
        MembershipStatus.objects.create(name='Pending Approval', description='Member application is pending approval.')

def remove_membership_statuses(apps, schema_editor):
    MembershipStatus = apps.get_model('members_amor108', 'MembershipStatus')
    MembershipStatus.objects.filter(name='Approved').delete()
    MembershipStatus.objects.filter(name='Rejected').delete()
    MembershipStatus.objects.filter(name='Pending Approval').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('members_amor108', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_membership_statuses, remove_membership_statuses),
    ]
