# Generated by Django 5.2.8 on 2025-12-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_amor108', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='share_ownership_details',
        ),
    ]
