# Generated by Django 5.2.8 on 2025-12-31 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_amor108', '0002_remove_member_share_ownership_details'),
        ('pools', '0003_resolution_no_votes_resolution_yes_votes_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pools.pool'),
        ),
    ]
