# Generated by Django 5.2.8 on 2025-11-29 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_director',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'director'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
