import os
import csv
from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from members.models import Member
from datetime import datetime

User = get_user_model()

class Command(BaseCommand):
    help = 'Seed the database with member data from CSV and AMOR108'
    
    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Clear all existing member data before seeding',
        )
        parser.add_argument(
            '--test',
            action='store_true',
            help='Create test data instead of real data',
        )
    
    def handle(self, *args, **options):
        admin_user = User.objects.filter(is_superuser=True).first()
        if not admin_user:
            admin_user = User.objects.create_superuser(
                username='admin',
                email='admin@example.com',
                password='admin123'
            )
        
        if options['clear']:
            self.stdout.write(self.style.WARNING('Clearing all existing member data...'))
            Member.objects.all().delete()
            self.stdout.write(self.style.SUCCESS('All member data cleared.'))
        
        if options['test']:
            self.create_test_members(admin_user)
        else:
            self.create_real_members(admin_user)
    
    def create_real_members(self, admin_user):
        """Seed the database with real member data"""
        
        member_data = [
            # CSV Members (31)
            {
                'member_id': 'CSV001',
                'full_name': 'Anna Awounder',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 43200.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV002',
                'full_name': 'Christine Guda',
                'phone': '713698900',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'COMPLETE',
                'total_amount': 142901.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV003',
                'full_name': 'Collins Millimu',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 24000.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV004',
                'full_name': 'David Thomas',
                'phone': '726882826',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'COMPLETE',
                'total_amount': 244024.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV005',
                'full_name': 'Edna Mayada',
                'phone': '723279975',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'COMPLETE',
                'total_amount': 84582.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV006',
                'full_name': 'Esther Mwai',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 27360.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV007',
                'full_name': 'Gloria nan',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 8929.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV008',
                'full_name': 'Hadassa Muiru',
                'phone': '728838166',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'COMPLETE',
                'total_amount': 108454.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV009',
                'full_name': 'Isaack Kamau',
                'phone': '726606429',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'COMPLETE',
                'total_amount': 52131.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV010',
                'full_name': 'Jane Wambui',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'REVIEW',
                'contact_status': 'MISSING_PHONE',
                'total_amount': -100000.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'Negative balance'
            },
            {
                'member_id': 'CSV011',
                'full_name': 'Kanyi Joseph',
                'phone': '722766168',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'COMPLETE',
                'total_amount': 126609.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV012',
                'full_name': 'Keneth Amalo',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 17760.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV013',
                'full_name': 'Laura Nganga',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 71397.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV014',
                'full_name': 'Loise Wanjiru',
                'phone': '726493215',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'COMPLETE',
                'total_amount': 38845.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV015',
                'full_name': 'Lucy Omenya',
                'phone': '705477355',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'COMPLETE',
                'total_amount': 30274.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV016',
                'full_name': 'Margaret Njoki',
                'phone': '720771524',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'COMPLETE',
                'total_amount': 154623.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV017',
                'full_name': 'Mary Okwach',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 6000.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV018',
                'full_name': 'Maureen Awuor',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 31276.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV019',
                'full_name': 'Miroslav Muthoni',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'REVIEW',
                'contact_status': 'MISSING_PHONE',
                'total_amount': -3960.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'Negative balance'
            },
            {
                'member_id': 'CSV020',
                'full_name': 'Mitesh Parmer',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 95652.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV021',
                'full_name': 'Paul Mutemi',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 116218.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV022',
                'full_name': 'Philip Nganga',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 126994.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV023',
                'full_name': 'Renny Achieng',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 139299.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV024',
                'full_name': 'Rodah Muturi',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 74400.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV025',
                'full_name': 'Tasha 2',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 75325.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV026',
                'full_name': 'Tereesa Ochieng',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 146992.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV027',
                'full_name': 'Teresia Karanja',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 30104.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV028',
                'full_name': 'Vincent Mburugu',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 24883.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV029',
                'full_name': 'Zacharia Kuria',
                'phone': '727815367',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'COMPLETE',
                'total_amount': 20658.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'CSV original'
            },
            {
                'member_id': 'CSV030',
                'full_name': 'Unknown Member 1',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_INFO',
                'total_amount': 1958930.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'Needs identification'
            },
            {
                'member_id': 'CSV031',
                'full_name': 'Unknown Member 2',
                'phone': '',
                'email': '',
                'data_source': 'CSV',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_INFO',
                'total_amount': 3917860.0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 0,
                'loan_amount': 0,
                'interest': 0,
                'bonus': 0,
                'notes': 'Needs identification'
            },
            # AMOR108 Members (16)
            {
                'member_id': 'AMR001',
                'full_name': 'Peter Kamori',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 0,
                'monthly_contribution': 312144.0,
                'shares': 30,
                'loan_amount': 90000.0,
                'interest': 9000.0,
                'bonus': 1800.0,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR002',
                'full_name': 'Kennedy Ndole',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 1700.0,
                'monthly_contribution': 11806.0,
                'shares': 1,
                'loan_amount': 118060.0,
                'interest': 11806.0,
                'bonus': 0,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR003',
                'full_name': 'Peter Mugo',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 3000.0,
                'monthly_contribution': 23619.0,
                'shares': 2,
                'loan_amount': 58000.0,
                'interest': 5800.0,
                'bonus': 1160.0,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR004',
                'full_name': 'Alicia Muli',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 1700.0,
                'monthly_contribution': 11806.0,
                'shares': 1,
                'loan_amount': 11806.0,
                'interest': 1180.6,
                'bonus': 0,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR005',
                'full_name': 'Whitney Wanjiku',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 1700.0,
                'monthly_contribution': 20083.0,
                'shares': 1,
                'loan_amount': 30000.0,
                'interest': 3000.0,
                'bonus': 600.0,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR006',
                'full_name': 'Magret Kamau',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 1,
                'loan_amount': 45000.0,
                'interest': 4000.0,
                'bonus': 800.0,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR007',
                'full_name': 'Queslly Waliaula',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 0,
                'monthly_contribution': 3600.0,
                'shares': 3,
                'loan_amount': 40699.4,
                'interest': 4069.94,
                'bonus': 813.98,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR008',
                'full_name': 'Lucy Wanjiru',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 1,
                'loan_amount': 60759.0,
                'interest': 6075.9,
                'bonus': 1215.18,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR009',
                'full_name': 'Rose Vusha',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 0,
                'monthly_contribution': 1200.0,
                'shares': 1,
                'loan_amount': 20000.0,
                'interest': 2000.0,
                'bonus': 400.0,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR010',
                'full_name': 'Magret Wanjiru',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 1,
                'loan_amount': 30000.0,
                'interest': 3000.0,
                'bonus': 600.0,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR011',
                'full_name': 'Eva Atieno',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 1,
                'loan_amount': 5500.0,
                'interest': 550.0,
                'bonus': 110.0,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR012',
                'full_name': 'Phelix Opana',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 0,
                'monthly_contribution': 1200.0,
                'shares': 1,
                'loan_amount': 7000.0,
                'interest': 700.0,
                'bonus': 140.0,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR013',
                'full_name': 'Mary Nyambura',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 0,
                'monthly_contribution': 0,
                'shares': 1,
                'loan_amount': 4500.0,
                'interest': 450.0,
                'bonus': 90.0,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR014',
                'full_name': 'David Kaka',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 0,
                'monthly_contribution': 1200.0,
                'shares': 1,
                'loan_amount': 5500.0,
                'interest': 550.0,
                'bonus': 110.0,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR015',
                'full_name': 'Thomas Kamau',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 4664.6,
                'monthly_contribution': 19436.0,
                'shares': 1,
                'loan_amount': 24101.0,
                'interest': 2410.1,
                'bonus': 480.22,
                'notes': 'AMOR108 member'
            },
            {
                'member_id': 'AMR016',
                'full_name': 'Mercy Owano',
                'phone': '',
                'email': '',
                'data_source': 'AMOR108',
                'status': 'ACTIVE',
                'contact_status': 'MISSING_PHONE',
                'total_amount': 0,
                'registration_fee': 6134.0,
                'monthly_contribution': 0,
                'shares': 1,
                'loan_amount': 25561.0,
                'interest': 2556.1,
                'bonus': 511.22,
                'notes': 'AMOR108 member'
            },
        ]
        
        created_count = 0
        updated_count = 0
        
        for member_info in member_data:
            member, created = Member.objects.update_or_create(
                member_id=member_info['member_id'],
                defaults={
                    'full_name': member_info['full_name'],
                    'phone': member_info['phone'] or None,
                    'email': member_info['email'] or None,
                    'data_source': member_info['data_source'],
                    'status': member_info['status'],
                    'contact_status': member_info['contact_status'],
                    'total_amount': member_info['total_amount'],
                    'registration_fee': member_info['registration_fee'],
                    'monthly_contribution': member_info['monthly_contribution'],
                    'shares': member_info['shares'],
                    'loan_amount': member_info['loan_amount'],
                    'interest': member_info['interest'],
                    'bonus': member_info['bonus'],
                    'notes': member_info['notes'],
                    'created_by': admin_user,
                    'updated_by': admin_user,
                }
            )
            
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'Created member: {member.member_id} - {member.full_name}'))
            else:
                updated_count += 1
                self.stdout.write(self.style.WARNING(f'Updated member: {member.member_id} - {member.full_name}'))
        
        self.stdout.write(self.style.SUCCESS(
            f'Successfully seeded {created_count + updated_count} members '
            f'({created_count} created, {updated_count} updated)'
        ))
    
    def create_test_members(self, admin_user):
        """Create a few test members for development"""
        test_members = [
            {
                'member_id': 'TEST001',
                'full_name': 'Test Member One',
                'phone': '0700123456',
                'email': 'test1@example.com',
                'data_source': 'MANUAL',
                'status': 'ACTIVE',
                'contact_status': 'COMPLETE',
                'total_amount': 10000,
                'registration_fee': 1000,
                'monthly_contribution': 5000,
                'shares': 5,
                'loan_amount': 2000,
                'interest': 200,
                'bonus': 100,
                'notes': 'Test member for development'
            },
            {
                'member_id': 'TEST002',
                'full_name': 'Test Member Two',
                'phone': '0700654321',
                'email': 'test2@example.com',
                'data_source': 'MANUAL',
                'status': 'PENDING',
                'contact_status': 'COMPLETE',
                'total_amount': 5000,
                'registration_fee': 500,
                'monthly_contribution': 2500,
                'shares': 2,
                'loan_amount': 1000,
                'interest': 100,
                'bonus': 50,
                'notes': 'Another test member'
            }
        ]
        
        for member_info in test_members:
            Member.objects.create(
                created_by=admin_user,
                updated_by=admin_user,
                **member_info
            )
        
        self.stdout.write(self.style.SUCCESS(f'Created {len(test_members)} test members'))
