# Generated by Django 5.2.8 on 2025-12-17 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('residential_area', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('passport_photo', models.ImageField(upload_to='passport_photos/')),
                ('nationality', models.CharField(max_length=100)),
                ('identification_card_no', models.CharField(blank=True, max_length=100)),
                ('passport_no', models.CharField(blank=True, max_length=100)),
                ('kin_names', models.CharField(max_length=255)),
                ('kin_mobile_no', models.CharField(max_length=20)),
                ('kin_email_address', models.EmailField(max_length=254)),
                ('kin_identification_passport_no', models.CharField(max_length=100)),
                ('kin_nationality', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
