# Generated by Django 5.2.8 on 2026-01-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('released', 'Released'), ('called', 'Called'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
