# Generated by Django 5.2.8 on 2025-11-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_financial_year_start', models.DateField(blank=True, null=True)),
                ('current_financial_year_end', models.DateField(blank=True, null=True)),
                ('max_loan_to_share_ratio', models.DecimalField(decimal_places=2, default=3.0, help_text='Maximum loan amount as a multiple of shares', max_digits=5)),
                ('min_credit_score_for_loan', models.IntegerField(default=550, help_text='Minimum credit score required for loan approval')),
                ('target_member_growth', models.DecimalField(decimal_places=2, default=0.1, help_text='Target annual member growth rate (e.g., 0.10 for 10%)', max_digits=5)),
                ('target_loan_portfolio_growth', models.DecimalField(decimal_places=2, default=0.15, help_text='Target annual loan portfolio growth rate (e.g., 0.15 for 15%)', max_digits=5)),
            ],
        ),
    ]
