# Generated by Django 5.2.8 on 2025-12-10 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_source', models.CharField(choices=[('CSV', 'CSV'), ('AMOR108', 'AMOR108'), ('MANUAL', 'Manual')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('REVIEW', 'Review'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=10)),
                ('contact_status', models.CharField(choices=[('COMPLETE', 'Complete'), ('MISSING_PHONE', 'Missing Phone'), ('MISSING_EMAIL', 'Missing Email'), ('MISSING_INFO', 'Missing Info')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shares', models.IntegerField(default=0)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
