# Generated by Django 5.2.8 on 2026-01-26 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('share_purchase', 'Share Purchase'), ('payment_due', 'Payment Due'), ('guarantee_request', 'Guarantee Request'), ('loan_pending_manager', 'Loan Pending Manager Review'), ('loan_manager_approved', 'Loan Approved by Manager'), ('loan_manager_rejected', 'Loan Rejected by Manager'), ('loan_pending_director', 'Loan Pending Director Review'), ('loan_director_approved', 'Loan Approved by Director'), ('loan_director_rejected', 'Loan Rejected by Director'), ('loan_fully_approved', 'Loan Fully Approved'), ('new_message', 'New Message')], max_length=50, unique=True)),
                ('subject_template', models.CharField(blank=True, max_length=255)),
                ('email_message_template', models.TextField(blank=True)),
                ('sms_message_template', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('share_purchase', 'Share Purchase'), ('payment_due', 'Payment Due'), ('guarantee_request', 'Guarantee Request'), ('loan_pending_manager', 'Loan Pending Manager Review'), ('loan_manager_approved', 'Loan Approved by Manager'), ('loan_manager_rejected', 'Loan Rejected by Manager'), ('loan_pending_director', 'Loan Pending Director Review'), ('loan_director_approved', 'Loan Approved by Director'), ('loan_director_rejected', 'Loan Rejected by Director'), ('loan_fully_approved', 'Loan Fully Approved'), ('new_message', 'New Message')], default='info', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
