# Generated by Django 5.2.8 on 2025-11-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('share_purchase', 'Share Purchase'), ('payment_due', 'Payment Due'), ('guarantee_request', 'Guarantee Request'), ('loan_pending_manager', 'Loan Pending Manager Review'), ('loan_manager_approved', 'Loan Approved by Manager'), ('loan_manager_rejected', 'Loan Rejected by Manager'), ('loan_pending_director', 'Loan Pending Director Review'), ('loan_director_approved', 'Loan Approved by Director'), ('loan_director_rejected', 'Loan Rejected by Director'), ('loan_fully_approved', 'Loan Fully Approved')], max_length=50, unique=True)),
                ('subject_template', models.CharField(blank=True, max_length=255)),
                ('email_message_template', models.TextField(blank=True)),
                ('sms_message_template', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('share_purchase', 'Share Purchase'), ('payment_due', 'Payment Due'), ('guarantee_request', 'Guarantee Request'), ('loan_pending_manager', 'Loan Pending Manager Review'), ('loan_manager_approved', 'Loan Approved by Manager'), ('loan_manager_rejected', 'Loan Rejected by Manager'), ('loan_pending_director', 'Loan Pending Director Review'), ('loan_director_approved', 'Loan Approved by Director'), ('loan_director_rejected', 'Loan Rejected by Director'), ('loan_fully_approved', 'Loan Fully Approved')], default='info', max_length=50),
        ),
    ]
