# Generated by Django 5.2.8 on 2025-12-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsetting_notificationtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('share_purchase', 'Share Purchase'), ('payment_due', 'Payment Due'), ('guarantee_request', 'Guarantee Request'), ('loan_pending_manager', 'Loan Pending Manager Review'), ('loan_manager_approved', 'Loan Approved by Manager'), ('loan_manager_rejected', 'Loan Rejected by Manager'), ('loan_pending_director', 'Loan Pending Director Review'), ('loan_director_approved', 'Loan Approved by Director'), ('loan_director_rejected', 'Loan Rejected by Director'), ('loan_fully_approved', 'Loan Fully Approved'), ('new_message', 'New Message')], default='info', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('share_purchase', 'Share Purchase'), ('payment_due', 'Payment Due'), ('guarantee_request', 'Guarantee Request'), ('loan_pending_manager', 'Loan Pending Manager Review'), ('loan_manager_approved', 'Loan Approved by Manager'), ('loan_manager_rejected', 'Loan Rejected by Manager'), ('loan_pending_director', 'Loan Pending Director Review'), ('loan_director_approved', 'Loan Approved by Director'), ('loan_director_rejected', 'Loan Rejected by Director'), ('loan_fully_approved', 'Loan Fully Approved'), ('new_message', 'New Message')], max_length=50, unique=True),
        ),
    ]
