# Generated by Django 5.2.8 on 2026-01-26 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('member_limit', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Automatically locked when member limit is reached.')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('allow_guarantees', models.BooleanField(default=False, help_text='Allows members of this pool to guarantee loans.')),
                ('guarantee_exposure_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum total amount a member can guarantee.', max_digits=12)),
                ('manager', models.ForeignKey(blank=True, help_text='The user responsible for managing this pool.', limit_choices_to={'user_type__in': ['director', 'admin', 'founder']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_pools', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='pools', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoolManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(limit_choices_to={'user_type__in': ['director', 'admin', 'founder']}, on_delete=django.db.models.deletion.CASCADE, related_name='pool_assignments', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='pools.pool')),
            ],
            options={
                'unique_together': {('pool', 'manager')},
            },
        ),
    ]
