# Generated by Django 5.2.8 on 2025-12-31 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('visible_to_all', models.BooleanField(default=True)),
                ('votable_by_gold_only', models.BooleanField(default=False, help_text='Only members of Gold tier pools can vote.')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resolutions', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(blank=True, help_text='The pool this resolution is specific to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions', to='pools.pool')),
            ],
        ),
    ]
