# Generated by Django 5.2.8 on 2025-12-31 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='no_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resolution',
            name='yes_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_choice', models.BooleanField(help_text="True for 'Yes', False for 'No'")),
                ('vote_date', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='pools.resolution')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vote_date'],
                'unique_together': {('resolution', 'voter')},
            },
        ),
    ]
