# Generated by Django 5.2.8 on 2025-12-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0003_resolution_no_votes_resolution_yes_votes_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='resolution',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.DeleteModel(
            name='Resolution',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
