# Generated by Django 5.2.8 on 2026-01-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_remove_vote_resolution_alter_vote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='allow_guarantees',
            field=models.BooleanField(default=False, help_text='Allows members of this pool to guarantee loans.'),
        ),
        migrations.AddField(
            model_name='pool',
            name='guarantee_exposure_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum total amount a member can guarantee.', max_digits=12),
        ),
    ]
