# Generated by Django 5.2.8 on 2026-01-26 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Amor108Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_clean_contribution_history', models.BooleanField(default=True)),
                ('outstanding_penalties_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('has_loan_arrears', models.BooleanField(default=False)),
                ('guarantee_exposure_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('voting_rights_revoked', models.BooleanField(default=False)),
                ('loan_visibility_reduced', models.BooleanField(default=False)),
                ('reduced_credit_power', models.BooleanField(default=False)),
                ('has_missed_contributions', models.BooleanField(default=False)),
                ('next_of_kin_names', models.CharField(blank=True, max_length=255)),
                ('next_of_kin_mobile_no', models.CharField(blank=True, max_length=15)),
                ('next_of_kin_email_address', models.EmailField(blank=True, max_length=254)),
                ('next_of_kin_identification_passport_no', models.CharField(blank=True, max_length=50)),
                ('next_of_kin_nationality', models.CharField(blank=True, max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('membership_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amor108_profiles', to='pools.pool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amor108_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_amor108.role')),
            ],
        ),
    ]
