# Generated by Django 5.2.8 on 2025-12-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_amor108', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amor108profile',
            name='guarantee_exposure_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='amor108profile',
            name='has_clean_contribution_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amor108profile',
            name='has_loan_arrears',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amor108profile',
            name='loan_visibility_reduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amor108profile',
            name='outstanding_penalties_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='amor108profile',
            name='reduced_credit_power',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amor108profile',
            name='voting_rights_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
