# Generated by Django 5.2.8 on 2025-12-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_amor108', '0002_amor108profile_guarantee_exposure_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amor108profile',
            name='has_missed_contributions',
            field=models.BooleanField(default=False),
        ),
    ]
