# Generated by Django 5.2.8 on 2025-12-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members_amor108', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_date', models.DateField(auto_now_add=True)),
                ('effective_date', models.DateField(help_text='Date from which shares are considered for this dividend')),
                ('dividend_rate', models.DecimalField(decimal_places=2, help_text='Dividend rate for this declaration (e.g., 0.05 for 5%)', max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.05, help_text='Tax rate applied to this dividend (e.g., 0.05 for 5%)', max_digits=5)),
                ('is_approved', models.BooleanField(default=False, help_text='Has this dividend declaration been approved for payment?')),
            ],
            options={
                'ordering': ['-declaration_date'],
            },
        ),
        migrations.CreateModel(
            name='ShareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_unit_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('dividend_rate', models.DecimalField(decimal_places=2, default=0.05, help_text='Annual dividend rate (e.g., 0.05 for 5%)', max_digits=5)),
                ('dividend_frequency_months', models.IntegerField(default=12, help_text='How often dividends are paid in months')),
                ('bonus_share_ratio', models.DecimalField(decimal_places=2, default=0.01, help_text='Ratio of bonus shares per unit (e.g., 0.01 for 1 bonus share per 100 units)', max_digits=5)),
                ('bonus_min_units', models.IntegerField(default=100, help_text='Minimum units required to qualify for bonus shares')),
                ('min_transfer_units', models.IntegerField(default=10, help_text='Minimum number of units that can be transferred')),
                ('withdrawal_period_days', models.IntegerField(default=30, help_text='Number of days notice required for share withdrawal')),
                ('dividend_tax_rate', models.DecimalField(decimal_places=2, default=0.05, help_text='Default tax rate on dividends (e.g., 0.05 for 5%)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monthly_share_target', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Target amount for monthly share contributions.', max_digits=12, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_account', to='members_amor108.member')),
            ],
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Share Purchase'), ('dividend', 'Dividend Payment'), ('bonus', 'Bonus Issue')], max_length=20)),
                ('units', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('dividend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='shares.dividend')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_transactions', to='members_amor108.member')),
            ],
        ),
    ]
