# Generated by Django 5.2.8 on 2025-11-29 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Share Purchase'), ('dividend', 'Dividend Payment'), ('bonus', 'Bonus Issue')], max_length=20)),
                ('units', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
