# Generated by Django 5.2.8 on 2025-11-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_unit_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('dividend_rate', models.DecimalField(decimal_places=2, default=0.05, help_text='Annual dividend rate (e.g., 0.05 for 5%)', max_digits=5)),
                ('dividend_frequency_months', models.IntegerField(default=12, help_text='How often dividends are paid in months')),
                ('bonus_share_ratio', models.DecimalField(decimal_places=2, default=0.01, help_text='Ratio of bonus shares per unit (e.g., 0.01 for 1 bonus share per 100 units)', max_digits=5)),
                ('bonus_min_units', models.IntegerField(default=100, help_text='Minimum units required to qualify for bonus shares')),
                ('min_transfer_units', models.IntegerField(default=10, help_text='Minimum number of units that can be transferred')),
                ('withdrawal_period_days', models.IntegerField(default=30, help_text='Number of days notice required for share withdrawal')),
            ],
        ),
    ]
