# Generated by Django 5.2.8 on 2025-12-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Share Purchase'), ('dividend', 'Dividend Payment'), ('bonus', 'Bonus Issue'), ('reinvestment', 'Profit Reinvestment')], max_length=20),
        ),
    ]
