# Generated by Django 5.2.8 on 2025-11-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_shareconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='monthly_share_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Target amount for monthly share contributions.', max_digits=12, null=True),
        ),
    ]
