# Generated by Django 5.2.8 on 2026-01-02 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0002_alter_guarantee_status'),
        ('shares', '0002_alter_sharetransaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_units', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guarantee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_lock', to='guarantees.guarantee')),
                ('share_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='shares.share')),
            ],
        ),
    ]
