# Generated by Django 5.2.8 on 2026-01-03 08:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_sharelock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='monthly_share_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Target amount for monthly share contributions.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
