# Generated by Django 5.2.8 on 2025-11-30 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_share_monthly_share_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_date', models.DateField(auto_now_add=True)),
                ('effective_date', models.DateField(help_text='Date from which shares are considered for this dividend')),
                ('dividend_rate', models.DecimalField(decimal_places=2, help_text='Dividend rate for this declaration (e.g., 0.05 for 5%)', max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.05, help_text='Tax rate applied to this dividend (e.g., 0.05 for 5%)', max_digits=5)),
                ('is_approved', models.BooleanField(default=False, help_text='Has this dividend declaration been approved for payment?')),
            ],
            options={
                'ordering': ['-declaration_date'],
            },
        ),
        migrations.AddField(
            model_name='shareconfig',
            name='dividend_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.05, help_text='Default tax rate on dividends (e.g., 0.05 for 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='dividend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='shares.dividend'),
        ),
    ]
