# Generated by Django 5.2.8 on 2026-01-26 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members_amor108', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Total interest rate as a decimal (e.g., 0.20 for 20%)', max_digits=5)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('max_term_months', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('eligibility_criteria', models.TextField(blank=True, help_text='Criteria for loan eligibility')),
                ('application_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_for_non_member', models.BooleanField(default=False, help_text='Check if this loan type is for non-members (guests).')),
                ('webbank_interest_share', models.DecimalField(decimal_places=2, default=0.0, help_text='Portion of interest for WebBank (e.g., 0.02 for 2%).', max_digits=5)),
                ('guarantor_interest_share', models.DecimalField(decimal_places=2, default=0.0, help_text='Portion of interest for the guarantor (e.g., 0.08 for 8%).', max_digits=5)),
                ('member_interest_share', models.DecimalField(decimal_places=2, default=0.0, help_text='Portion of interest to be distributed among all members (e.g., 0.10 for 10%).', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=20, unique=True)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('term_months', models.IntegerField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved_manager', 'Approved by Manager'), ('approved_director', 'Approved by Director'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('outstanding_principal', models.DecimalField(blank=True, decimal_places=2, help_text='Remaining principal balance', max_digits=12, null=True)),
                ('next_repayment_date', models.DateField(blank=True, null=True)),
                ('last_repayment_date', models.DateField(blank=True, null=True)),
                ('is_defaulted', models.BooleanField(default=False)),
                ('approval_stage', models.CharField(choices=[('pending_manager', 'Pending Manager Approval'), ('pending_director', 'Pending Director Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_manager', max_length=20)),
                ('manager_approval_date', models.DateTimeField(blank=True, null=True)),
                ('director_approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_deadline', models.DateTimeField(blank=True, null=True)),
                ('amor108_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_amor108_member', to='members_amor108.member')),
                ('director_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_director_approved', to=settings.AUTH_USER_MODEL)),
                ('guarantors', models.ManyToManyField(blank=True, help_text='Select members who will guarantee this loan', related_name='guaranteed_loans', to='members_amor108.member')),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_managed_approved', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_user', to=settings.AUTH_USER_MODEL)),
                ('sponsored_by', models.ForeignKey(blank=True, help_text='The WebBank member who is sponsoring this guest loan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('commented', 'Commented'), ('forwarded', 'Forwarded for Director Approval')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('overdue', 'Overdue')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
            ],
        ),
    ]
