# Generated by Django 5.2.8 on 2025-12-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('members_amor108', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='guest_first_name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='guest_last_name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='loan',
            name='is_defaulted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='next_repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='outstanding_principal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining principal balance', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='payment_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayment', to='payments.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members_amor108.member'),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Interest rate as a decimal (e.g., 0.01 for 1% per month)', max_digits=5),
        ),
    ]
