# Generated by Django 5.2.8 on 2025-11-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loantype',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Criteria for loan eligibility'),
        ),
        migrations.AddField(
            model_name='loantype',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
