# Generated by Django 5.2.8 on 2025-11-29 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loantype_application_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='guarantors',
            field=models.ManyToManyField(blank=True, help_text='Select members who will guarantee this loan', limit_choices_to={'user_type': 'member'}, related_name='guaranteed_loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
