# Generated by Django 5.2.8 on 2025-12-17 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loan_guest_email_remove_loan_guest_first_name_and_more'),
        ('members_amor108', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amor108_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_amor108_member', to='members_amor108.member'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
