# Generated by Django 5.2.8 on 2025-12-17 12:16
from decimal import Decimal
from django.db import migrations

def add_default_loan_types(apps, schema_editor):
    LoanType = apps.get_model('loans', 'LoanType')
    
    LoanType.objects.get_or_create(
        name='Long-term',
        defaults={
            'interest_rate': Decimal('0.01'), # 1% p.m.
            'max_amount': Decimal('1000000.00'),
            'min_amount': Decimal('10000.00'),
            'max_term_months': 60,
            'description': 'Standard long-term loan for members.',
            'eligibility_criteria': 'Active member for 6+ months, good contribution history.',
            'application_fee': Decimal('500.00'),
            'processing_fee': Decimal('1000.00'),
        }
    )
    LoanType.objects.get_or_create(
        name='Emergency',
        defaults={
            'interest_rate': Decimal('0.10'), # 10% p.m.
            'max_amount': Decimal('50000.00'),
            'min_amount': Decimal('1000.00'),
            'max_term_months': 6,
            'description': 'Quick loan for emergencies.',
            'eligibility_criteria': 'Active member for 3+ months, fair contribution history.',
            'application_fee': Decimal('100.00'),
            'processing_fee': Decimal('200.00'),
        }
    )
    LoanType.objects.get_or_create(
        name='Non-member',
        defaults={
            'interest_rate': Decimal('0.20'), # 20% p.m.
            'max_amount': Decimal('10000.00'),
            'min_amount': Decimal('500.00'),
            'max_term_months': 3,
            'description': 'Short-term loan for non-members (higher interest).',
            'eligibility_criteria': 'Valid ID and contact. Subject to external credit check.',
            'application_fee': Decimal('200.00'),
            'processing_fee': Decimal('500.00'),
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_amor108_member_alter_loan_member'),
    ]

    operations = [
        migrations.RunPython(add_default_loan_types, migrations.RunPython.noop),
    ]
