# Generated by Django 5.2.8 on 2025-12-30 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_add_default_loan_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='sponsored_by',
            field=models.ForeignKey(blank=True, help_text='The WebBank member who is sponsoring this guest loan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
