# Generated by Django 5.2.8 on 2026-01-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_sponsored_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='guarantor_interest_share',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Portion of interest for the guarantor (e.g., 0.08 for 8%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='loantype',
            name='is_for_non_member',
            field=models.BooleanField(default=False, help_text='Check if this loan type is for non-members (guests).'),
        ),
        migrations.AddField(
            model_name='loantype',
            name='member_interest_share',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Portion of interest to be distributed among all members (e.g., 0.10 for 10%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='loantype',
            name='webbank_interest_share',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Portion of interest for WebBank (e.g., 0.02 for 2%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Total interest rate as a decimal (e.g., 0.20 for 20%)', max_digits=5),
        ),
    ]
