# Generated by Django 5.2.8 on 2026-01-06 14:35

from django.db import migrations
from decimal import Decimal

def create_default_loan_types(apps, schema_editor):
    """
    Creates the default loan types for members and non-members.
    """
    LoanType = apps.get_model('loans', 'LoanType')

    # 1. Non-Member Loan (20% interest)
    LoanType.objects.update_or_create(
        name="Non-Member Guest Loan",
        defaults={
            'is_for_non_member': True,
            'interest_rate': Decimal('0.20'),
            'webbank_interest_share': Decimal('0.02'),
            'guarantor_interest_share': Decimal('0.08'),
            'member_interest_share': Decimal('0.10'),
            'max_term_months': 12,
            'min_amount': Decimal('5000.00'),
            'max_amount': Decimal('100000.00'),
            'description': "Loan for non-members, guaranteed by a WebBank member.",
            'eligibility_criteria': "Must be sponsored and guaranteed by an active WebBank member.",
        }
    )

    # 2. Member Short-Term Loan (10% for 1 month)
    LoanType.objects.update_or_create(
        name="Member Short-Term Loan",
        defaults={
            'is_for_non_member': False,
            'interest_rate': Decimal('0.10'),
            'member_interest_share': Decimal('0.10'), # All interest distributed to members
            'max_term_months': 1,
            'min_amount': Decimal('1000.00'),
            'max_amount': Decimal('50000.00'),
            'description': "A one-month loan for active members.",
            'eligibility_criteria': "Must be an active member for at least 3 months.",
        }
    )

    # 3. Member Long-Term Loan (1% per month)
    LoanType.objects.update_or_create(
        name="Member Long-Term Loan",
        defaults={
            'is_for_non_member': False,
            'interest_rate': Decimal('0.12'), # 1% per month = 12% per year
            'member_interest_share': Decimal('0.12'), # All interest distributed to members
            'max_term_months': 24,
            'min_amount': Decimal('10000.00'),
            'max_amount': Decimal('500000.00'),
            'description': "A long-term loan for active members, with interest calculated monthly.",
            'eligibility_criteria': "Must be an active member for at least 6 months with consistent contributions.",
        }
    )

def reverse_default_loan_types(apps, schema_editor):
    """
    Removes the default loan types.
    """
    LoanType = apps.get_model('loans', 'LoanType')
    LoanType.objects.filter(
        name__in=[
            "Non-Member Guest Loan",
            "Member Short-Term Loan",
            "Member Long-Term Loan",
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loantype_guarantor_interest_share_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_loan_types, reverse_code=reverse_default_loan_types),
    ]