# Generated by Django 5.2.8 on 2026-01-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_create_default_loan_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrepayment',
            name='amount',
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
