# Generated by Django 5.2.8 on 2025-12-31 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pools', '0004_remove_vote_resolution_alter_vote_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('visible_to_all', models.BooleanField(default=True)),
                ('votable_by_gold_only', models.BooleanField(default=False, help_text='Only members of Gold tier pools can vote.')),
                ('vote_type', models.CharField(choices=[('ADVISORY', 'Advisory'), ('BINDING', 'Binding')], default='BINDING', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, help_text='Date and time when voting closes.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this resolution currently open for voting?')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('yes_votes', models.PositiveIntegerField(default=0)),
                ('no_votes', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resolutions', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(blank=True, help_text='The pool this resolution is specific to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions', to='pools.pool')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_choice', models.BooleanField(help_text="True for 'Yes', False for 'No'")),
                ('vote_date', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.resolution')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vote_date'],
                'unique_together': {('resolution', 'voter')},
            },
        ),
    ]
