# Generated by Django 5.2.8 on 2026-01-26 04:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('members_amor108', '0001_initial'),
        ('shares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_webbank_share', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_earnings', to='members_amor108.member')),
                ('repayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_distributions', to='loans.loanrepayment')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Q1 2025 Profit Distribution', max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_profit_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total profit generated in this cycle from all sources.', max_digits=15)),
                ('total_distributed_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total profit distributed to members in this cycle.', max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Calculation'), ('CALCULATED', 'Calculated'), ('DISTRIBUTED', 'Distributed'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('distributed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_profit', models.DecimalField(decimal_places=2, help_text='Gross profit allocated to this member.', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, help_text='Net profit after tax.', max_digits=12)),
                ('action', models.CharField(choices=[('PENDING', 'Pending Member Action'), ('WITHDRAWN', 'Withdrawn'), ('REINVESTED', 'Reinvested'), ('FORFEITED', 'Forfeited')], default='PENDING', max_length=20)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_profits', to='members_amor108.member')),
                ('reinvestment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinvested_profit', to='shares.sharetransaction')),
                ('profit_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_profits', to='profits.profitcycle')),
            ],
            options={
                'ordering': ['-profit_cycle__end_date', 'member__user__username'],
                'unique_together': {('profit_cycle', 'member')},
            },
        ),
    ]
