# Generated by Django 5.2.8 on 2025-12-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0001_initial'),
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofit',
            name='reinvestment_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinvested_profit', to='shares.sharetransaction'),
        ),
    ]
