# Generated by Django 5.2.8 on 2026-01-05 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_remove_loanrepayment_amount_and_more'),
        ('members_amor108', '0003_alter_member_pool'),
        ('profits', '0002_alter_memberprofit_reinvestment_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_webbank_share', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_earnings', to='members_amor108.member')),
                ('repayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_distributions', to='loans.loanrepayment')),
            ],
        ),
    ]
