# Generated by Django 5.2.8 on 2026-01-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members_amor108', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('transaction_code', models.CharField(blank=True, help_text='Transaction code from payment gateway', max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='MPESA', max_length=50)),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if the contribution has been verified.')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='members_amor108.member')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributions.contributionstatus')),
            ],
        ),
    ]
