# Generated by Django 5.2.8 on 2025-12-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the contribution has been verified.'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='MPESA', max_length=50),
        ),
        migrations.AddField(
            model_name='contribution',
            name='transaction_code',
            field=models.CharField(blank=True, help_text='Transaction code from payment gateway', max_length=100, null=True),
        ),
    ]
