# Generated by Django 5.2.8 on 2025-12-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_contribution_due_date_contribution_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
