# Generated by Django 5.2.8 on 2025-12-17 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, help_text="Unique ID from payment gateway (e.g., M-Pesa 'KQG123XYZ')", max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KSH', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('INITIATED', 'Initiated')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('MPESA_PAYBILL', 'M-Pesa Paybill'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='MPESA_PAYBILL', max_length=50)),
                ('sender_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shortcode', models.CharField(blank=True, help_text='The Paybill or Till number', max_length=20, null=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Reference number from sender (e.g., account number)', max_length=100, null=True)),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for reconciliation or manual actions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
                ('related_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='contributions.contribution')),
            ],
            options={
                'ordering': ['-transaction_time'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(default='M-Pesa', max_length=50)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(help_text='Raw payload received from the payment gateway.')),
                ('is_processed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Any issues encountered during processing or manual review notes.')),
                ('related_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_log', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-log_time'],
            },
        ),
    ]
