# Generated by Django 5.2.8 on 2025-12-31 09:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOAN_APPLY', 'Loan Application'), ('LOAN_APPROVE', 'Loan Approval'), ('LOAN_REJECT', 'Loan Rejection'), ('LOAN_DISBURSE', 'Loan Disbursement'), ('LOAN_REPAY', 'Loan Repayment'), ('CONTRIBUTION_MADE', 'Contribution Made'), ('CONTRIBUTION_VERIFIED', 'Contribution Verified'), ('PROFIT_WITHDRAWN', 'Profit Withdrawn'), ('PROFIT_REINVESTED', 'Profit Reinvested'), ('POOL_JOIN', 'Pool Joined'), ('POOL_UPGRADE', 'Pool Upgraded'), ('POOL_CREATE', 'Pool Created'), ('RESOLUTION_CREATE', 'Resolution Created'), ('RESOLUTION_VOTE', 'Resolution Voted'), ('MEMBER_REGISTER', 'Member Registration'), ('MEMBER_APPROVE', 'Member Approved'), ('RULE_CHANGE', 'System Rule Change'), ('ADMIN_ACTION', 'Administrator Action'), ('PROFILE_UPDATE', 'Profile Update'), ('SHARE_PURCHASE', 'Share Purchase'), ('SHARE_TRANSFER', 'Share Transfer')], editable=False, max_length=50)),
                ('description', models.TextField(editable=False, help_text='Detailed description of the action.')),
                ('model_name', models.CharField(blank=True, editable=False, help_text="Name of the model affected (e.g., 'Loan', 'Contribution').", max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, editable=False, help_text='PK of the object affected (e.g., UUID or int).', max_length=36, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(blank=True, editable=False, help_text='User who performed the action (or None for system actions).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
