# Generated by Django 5.2.8 on 2026-01-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOAN_APPLY', 'Loan Application'), ('LOAN_APPROVE', 'Loan Approval'), ('LOAN_REJECT', 'Loan Rejection'), ('LOAN_DISBURSE', 'Loan Disbursement'), ('LOAN_REPAY', 'Loan Repayment'), ('LOAN_DEFAULTED', 'Loan Defaulted'), ('GUARANTEE_CALLED', 'Guarantee Called'), ('CONTRIBUTION_MADE', 'Contribution Made'), ('CONTRIBUTION_VERIFIED', 'Contribution Verified'), ('PROFIT_WITHDRAWN', 'Profit Withdrawn'), ('PROFIT_REINVESTED', 'Profit Reinvested'), ('POOL_JOIN', 'Pool Joined'), ('POOL_UPGRADE', 'Pool Upgraded'), ('POOL_CREATE', 'Pool Created'), ('RESOLUTION_CREATE', 'Resolution Created'), ('RESOLUTION_VOTE', 'Resolution Voted'), ('MEMBER_REGISTER', 'Member Registration'), ('MEMBER_APPROVE', 'Member Approved'), ('RULE_CHANGE', 'System Rule Change'), ('ADMIN_ACTION', 'Administrator Action'), ('PROFILE_UPDATE', 'Profile Update'), ('SHARE_PURCHASE', 'Share Purchase'), ('SHARE_TRANSFER', 'Share Transfer')], editable=False, max_length=50),
        ),
    ]
