# Generated by Django 5.2.8 on 2025-12-15 09:47

from django.db import migrations

def create_pools(apps, schema_editor):
    Pool = apps.get_model('amor108', 'Pool')
    pools_data = [
        {'name': '12 members contributing Ksh 10,000 per month', 'contribution_amount': 10000, 'contribution_frequency': 'monthly'},
        {'name': '12 members contributing Ksh 7,500 per month', 'contribution_amount': 7500, 'contribution_frequency': 'monthly'},
        {'name': '12 members contributing Ksh 5,000 per month', 'contribution_amount': 5000, 'contribution_frequency': 'monthly'},
        {'name': '24 members contributing Ksh 2,500 per month', 'contribution_amount': 2500, 'contribution_frequency': 'monthly'},
        {'name': '48 members contributing Ksh 1,000 per month', 'contribution_amount': 1000, 'contribution_frequency': 'monthly'},
        {'name': '60 members contributing Ksh 500 per month', 'contribution_amount': 500, 'contribution_frequency': 'monthly'},
        {'name': '12 members contributing Ksh 100 per day per month', 'contribution_amount': 100, 'contribution_frequency': 'daily'},
        {'name': '132 members contributing Ksh 50 per day per month', 'contribution_amount': 50, 'contribution_frequency': 'daily'},
    ]
    for pool_data in pools_data:
        Pool.objects.create(**pool_data)

class Migration(migrations.Migration):

    dependencies = [
        ('amor108', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_pools),
    ]
