# Generated by Django 5.2.8 on 2025-12-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amor108', '0001_initial'),
        ('members_amor108', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members_amor108.member'),
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members_amor108.member'),
        ),
    ]
