# Generated by Django 5.2.8 on 2025-12-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amor108', '0002_initial'),
        ('members_amor108', '0003_alter_member_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
    ]
